### ISSUE TITLE
Issue with passing tests

### ISSUE THREAD

**Issue by Benjamintdk** [FR-DC/FRDC-ML#26]
# Description
Get error message while attempting to run `pytest` to verify setup of the repository to access the dataset. 
![image](https://github.com/FR-DC/FRDC-ML/assets/45474952/f6ee1680-cdb7-4283-bda5-afc2b312de31)
Issue seems to be with torch 2.1.0, refer to [this](https://stackoverflow.com/questions/76327419/valueerror-libcublas-so-0-9-not-found-in-the-system-path)

# Possible fix
Upgrade to torch 2.1.1

**Comment by Eve-ning** [comment]
Yea it's a bit of a pain, I recommend to just `pip install torch` manually instead of relying on `poetry` specifically for torch.
The next release (sprint) will remove this dependency from our `pyproject.toml` as it's flaky. [67dd4f0](https://github.com/FR-DC/FRDC-ML/pull/28/commits/67dd4f072abda7968c5f8b7cef3e8bf9fb0f8023)

Furthermore, make sure that the `LD_LIBRARY_PATH` is also present in the venv
https://stackoverflow.com/questions/48428415/importerror-libcublas-so-9-0-cannot-open-shared-object-file

**Comment by Benjamintdk** [comment]
I see, hmm, why not use the fix of upgrading it to the later version of torch, or pinning it back to a slightly older and more stable version?

**Comment by Eve-ning** [comment]
I believe your fix would be fine if everyone is using linux but for windows, the pip install needs to include another index

[Source](https://pytorch.org/get-started/locally/)
Windows
```shell
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```
Linux
```shell
pip3 install torch torchvision torchaudio
```

so when windows systems try to `poetry install`, it omits the index, and install the **CPU** only version. I'd rather not try to maintain fixes for this problem to be honest, it's easier to just ask people to download it manually
